### PR TITLE
Fix `DE_94` & `DE_CMC` color difference metrics

### LINKED ISSUE #438: Non-standard implementation of `DE_CMC` and `DE_94`
The CMC(l:c) color difference model quantifies the difference from a standard (reference) color. 
https://en.wikipedia.org/wiki/Color_difference#CMC_l:c_(1984)

However, the current implementation uses the mean value as the "standard" rather than one of the `colordiff` inputs.
https://github.com/JuliaGraphics/Colors.jl/blob/efdb8a569e1607517e986fa01a51f6e41ab9cbd0/src/differences.jl#L328-L329
The comment implies that it is intentional rather than a mistake, but the averaging is not the original method. Even if we were to follow the method of using the mean values, the following uses `a.l` instead of `ml`, which is not consistent.
https://github.com/JuliaGraphics/Colors.jl/blob/efdb8a569e1607517e986fa01a51f6e41ab9cbd0/src/differences.jl#L338-L343

Although CMC (l:c) is an old model, it appears to still be used in the textile industry, as it is included in the ISO 105-J03 standard.

In practice, there seems to be a method of substituting a reference with an average color of multiple samples of the same product when no reference is available, but that is not the same as averaging inside `colordiff`.

However, this fix is too drastic to be at the patch level, so I would like to fix this in v0.13.0.

### PR DESCRIPTION
**Pull request by kimikage**
This makes `DE_94` and `DE_CMC` quasimetric. Within those metrics, the first argument of `colordiff` is taken as the reference color. This adds the weight parameters `k1` and `k2` to `DE_94`.

This also makes the omission of the metric constructor arguments more flexible.

~**Edit:** `DE_94` seems to have a similar problem. I will fix it as well.~ Done

Fixes #438

### CODE REVIEW

File: src/differences.jl [hunk 1]
```diff
@@ -365,7 +371,7 @@ end
 function _colordiff(ai::Color, bi::Color, m::DE_BFD)
     # Currently, support for the `wp` argument of `convert` is limited.
     function to_xyz(c::Color, wp)
-        c isa XYZ && return ai
+        c isa XYZ && return c
```
Comment (kimikage) [inline src/differences.jl:374]: :sob:

I am not going to backport this to v0.12. As a workaround, if the second argument is `XYZ`, please convert it to something other than `XYZ` (e.g. `xyY`).
